### ISSUE TITLE
"UnsatisfiableError" during installation

### ISSUE THREAD

**Issue by YePererva** [yfukasawa/LongQC#22]
Hello! I encountered several errors while installing. Please, help to solve it.

Steps to reproduce:
1. Install Anaconda 3:
```
# install anaconda prerequisites
sudo apt install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6
# install anaconsa itself
cd ./Downloads
wget https://repo.anaconda.com/archive/Anaconda3-2020.11-Linux-x86_64.sh
bash ./Anaconda3-2020.11-Linux-x86_64.sh
# allow to install to /home/username/anaconda3
# reject running conda init at start-up of system
# add conda to system $PATH varialbe
export PATH="/home/username/anaconda3/bin:$PATH"
```
This part works fine. 
2.  Install prerequisites, as described in README.md file:
```
# the following line works without problem:
conda install h5py
# the next line returns the 'UnsatisfiableError'
conda install -c bioconda pysam
# the following line works without problem:
conda install -c bioconda edlib
# the next line returns the 'UnsatisfiableError'
conda install -c bioconda python-edlib
```

The error message for `pysam` is:
```
~$ conda install -c bioconda pysam
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

The error message for `python-edlib` is:
```
~$ conda install -c bioconda python-edlib
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

System info: 
- OS : Ubuntu 20.04.2 LTS x64

**Comment by Jake-Goodall** [comment]
I'm having the exact same issue on my MAC. A fix would be greatly appreciated.

**Comment by yfukasawa** [comment]
Hello @YePererva and @Jake-Goodall,

Sorry for late checking but thanks for contacting!!
I'm now trying to reproduce the issue, tentatively installing ubuntu20.04 on a VM.
I feel this might have been caused by your python version, which could be out of support in pysam and python-edlib. e.g. your python might be a newer one than the ones supported.
conda, pysam, and python-elib are all supported by different teams; sometimes this kind of conflict happens.  

Can I ask your python version?
`python --version`

Yoshinori

**Comment by YePererva** [comment]
@yfukasawa, thank you for your responce!

I'm using Python 3.8.5
Is there any other info I should provide?

**Comment by yfukasawa** [comment]
Hi @YePererva ,

Thank you for sharing python version.
I've tried on VM using both python3.8 and python3.7, and I could reproduce the issue if I use python3.8.
It seems that conda packages of pysam/python-edlib are not compatible with python3.8 yet (not checked their specs carefully, but at least I got the same error).

I'll slightly modify the docker image, but tentative suggestion would be downgrading of your conda python to 3.7 or lower version.
`conda install python=3.7`
then, install other dependencies.

Hope this helps.
Yoshinori

**Comment by grpiccoli** [comment]
Hi @yfukasawa 

I was having the same error and found out that it is fixed with python 3.9 

I built the following Docker image
https://hub.docker.com/repository/docker/grpiccoli/longqc

The Dockerfile is here: 
https://github.com/grpiccoli/longqc.nf/blob/master/Dockerfile

**Comment by grpiccoli** [comment]
No worries, thank you for this useful tool, I just updated the docker image in dockerhub to be compatible with singularity, nextflow, snakemake and it uses alpine image to save a little space. I'm updating dockerfile as well in case it might be useful
Best
G

**Comment by kim-fehl** [comment]
Still getting this error when using file downloaded from the Releases. Has it been updated?

**Comment by yfukasawa** [comment]
Hi @kim-fehl, thanks for a reminder!
Updated the Dockerfile, and it should be available in 1.2.0c. Let me know if this doesn't work for you.

**Comment by hbadrane** [comment]
> Hi @yfukasawa
> 
> I was having the same error and found out that it is fixed with python 3.9
> 
> I built the following Docker image https://hub.docker.com/repository/docker/grpiccoli/longqc
> 
> The Dockerfile is here: https://github.com/grpiccoli/longqc.nf/blob/master/Dockerfile

Hello could you please explain some details on how to run it with singularity, I pulled the docker image as a sif file...
