### ISSUE TITLE
UnboundLocalError: local variable 'tuple_3'

### ISSUE THREAD

**Issue by msevi** [yfukasawa/LongQC#9]
Hello,
I've just installed the software. When running:
```
conda activate LongQC_env
export PATH=/home/m.sevi/software/LongQC/minimap2_mod/:$PATH
python /home/m.sevi/software/LongQC/longQC.py sampleqc -p 4 -x ont-rapid -o fne_qc_out_dir /scratch/m.sevi/processing/WW_HRSD/data/long/basecalled_fq/fne/fne_fastq/fne.fastq
```

**The run fails with standard output:**

> longQC:2020-06-18 15:11:19,615:166:INFO:Cmd: /home/m.sevi/software/LongQC/longQC.py sampleqc -p 4 -x ont-rapid -o fne_qc_out_dir /scratch/m.sevi/processing/WW_HRSD/data/long/basecalled_fq/fne/fne_fastq/fne.fastq
> longQC:2020-06-18 15:11:19,615:216:INFO:Preset "ont-rapid" was applied. Options --pb(--ont) is overwritten.
> longQC:2020-06-18 15:11:21,621:288:INFO:Computation of the low complexity region started for a chunk 0
> lq_mask:2020-06-18 15:11:22,791:111:INFO:New job was submitted: in->fne_qc_out_dir/analysis/tmp_0.fastq, out->fne_qc_out_dir/analysis/tmp_0.txt
> longQC:2020-06-18 15:11:22,792:293:INFO:Adapter search is starting for a chunk 0.
> longQC:2020-06-18 15:11:22,792:309:INFO:Computation of the GC fraction started for a chunk 0
> lq_utils:2020-06-18 15:11:25,979:380:INFO:list for subsample is not initialized. Initializing now.
> lq_adapt:2020-06-18 15:11:30,810:76:INFO:7038 reads were skipped due to their short lengths.
> lq_adapt:2020-06-18 15:11:30,811:96:INFO:Adapter Sequence: GTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCA, max identity:-1.000000 and the number of trimmed reads: 0
> longQC:2020-06-18 15:11:45,124:320:INFO:Adapter search has done for a chunk 0.
> longQC:2020-06-18 15:11:45,125:324:INFO:subsample finished for chunk 0.
> Traceback (most recent call last):
>   File "/home/m.sevi/software/LongQC/longQC.py", line 920, in <module>
>     main(args)
>   File "/home/m.sevi/software/LongQC/longQC.py", line 63, in main
>     args.handler(args)
>   File "/home/m.sevi/software/LongQC/longQC.py", line 335, in command_sample
>     if tuple_3:
> UnboundLocalError: local variable 'tuple_3' referenced before assignment

Below find information about my environment:

_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.1.1                      0    anaconda
certifi                   2020.4.5.2               py37_0    anaconda
cycler                    0.10.0                     py_2    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
edlib                     1.2.3                h2d50403_1    bioconda
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
glib                      2.63.1               h3eb4bd4_1  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
h5py                      2.10.0           py37h7918eee_0  
hdf5                      1.10.4               hb1b8bf9_0  
icu                       58.2              hf484d3e_1000    conda-forge
intel-openmp              2019.4                      243  
jinja2                    2.11.2                     py_0    anaconda
joblib                    0.15.1                     py_0    anaconda
jpeg                      9d                   h516909a_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.17.1               h173b8e3_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.69.1               h20c2e04_0  
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hed695b0_1    conda-forge
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               he19cac6_1  
markupsafe                1.1.1            py37h7b6447c_0    anaconda
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py37hef1b27d_0  
mkl                       2019.4                      243  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.14           py37hd81dba3_0    r
mkl_random                1.0.4            py37hd81dba3_0    r
ncurses                   6.2                  he6710b0_1  
numpy                     1.17.0           py37h7e9f1db_0    r
numpy-base                1.17.0           py37hde5b4d6_0    r
openssl                   1.1.1g               h7b6447c_0    anaconda
pandas                    1.0.4            py37h0573a6f_0    anaconda
pcre                      8.44                 he1b5a44_0    conda-forge
pip                       20.1.1                   py37_1  
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_4    conda-forge
pysam                     0.16.0.1         py37hc501bad_0    bioconda
python                    3.7.7                hcff3b4d_5  
python-dateutil           2.8.1                      py_0    anaconda
python-edlib              1.3.8.post1      py37h99015e2_1    bioconda
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                     py_0    anaconda
qt                        5.9.7                h5867ecd_1  
readline                  8.0                  h7b6447c_0  
scikit-learn              0.22.1           py37hd81dba3_0    anaconda
scipy                     1.4.1            py37h0b6359f_0    anaconda
setuptools                47.3.0                   py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.15.0                     py_0  
sqlite                    3.31.1               h62c20be_1  
tk                        8.6.8                hbc83047_0  
tornado                   6.0.4            py37h8f50634_1    conda-forge
wheel                     0.34.2                   py37_0  
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3

I'd appreciate any feedback.

Thank you,
Maria

**Comment by yfukasawa** [comment]
Hello @msevi,

Sorry for the issue, but thank you for your interest and raising this point!
There was a bug for adapter search part, and I fixed and pushed a new version.

Could you please try new one, version 1.1.1?

Yoshi

**Comment by msevi** [comment]
Hello Yoshi,
Thanks for your reply. I cloned the newest version and re ran, but the same error persists.

Cheers,
Maria

**Comment by yfukasawa** [comment]
Hello @msevi,

Thank you for trying, and I'm sorry for the issue. I forgot to upload the most important file...
Now, it should be working, and could you please try again?

Yoshi

**Comment by msevi** [comment]
Hi Yoshi,
Thanks for your help, processes finished without error!

Cheers,
Maria

**Comment by yfukasawa** [comment]
Hi Maria,

I'm glad to hear that it worked, and thank you for your kind update!

Best,
Yoshi
